# Generated by Django 4.0.6 on 2022-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todolists_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
