# Generated by Django 4.0.6 on 2022-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_todolists_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitems',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
